name: WiFiy (Windows + Android)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI workloads
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore WiFiy.sln

    - name: Build Android (Release)
      run: dotnet build WiFiy/WiFiy.csproj -c Release -f:net8.0-android

    - name: Build Windows (Release)
      run: dotnet build WiFiy/WiFiy.csproj -c Release -f:net8.0-windows10.0.19041.0

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Android artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          **/bin/Release/net8.0-android/**/*.apk
          **/bin/Release/net8.0-android/**/*.aab
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          **/bin/Release/net8.0-windows10.0.19041.0/**/*.exe
          **/bin/Release/net8.0-windows10.0.19041.0/**/*.msix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
